(cl:defpackage book_find-msg
  (:use )
  (:export
   "<FINDBOOKACTION>"
   "FINDBOOKACTION"
   "<FINDBOOKACTIONFEEDBACK>"
   "FINDBOOKACTIONFEEDBACK"
   "<FINDBOOKACTIONGOAL>"
   "FINDBOOKACTIONGOAL"
   "<FINDBOOKACTIONRESULT>"
   "FINDBOOKACTIONRESULT"
   "<FINDBOOKFEEDBACK>"
   "FINDBOOKFEEDBACK"
   "<FINDBOOKGOAL>"
   "FINDBOOKGOAL"
   "<FINDBOOKRESULT>"
   "FINDBOOKRESULT"
  ))

