; Auto-generated. Do not edit!


(cl:in-package book_find-msg)


;//! \htmlinclude FindBookGoal.msg.html

(cl:defclass <FindBookGoal> (roslisp-msg-protocol:ros-message)
  ((book_name
    :reader book_name
    :initarg :book_name
    :type cl:string
    :initform "")
   (book_storage
    :reader book_storage
    :initarg :book_storage
    :type cl:string
    :initform ""))
)

(cl:defclass FindBookGoal (<FindBookGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindBookGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindBookGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name book_find-msg:<FindBookGoal> is deprecated: use book_find-msg:FindBookGoal instead.")))

(cl:ensure-generic-function 'book_name-val :lambda-list '(m))
(cl:defmethod book_name-val ((m <FindBookGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader book_find-msg:book_name-val is deprecated.  Use book_find-msg:book_name instead.")
  (book_name m))

(cl:ensure-generic-function 'book_storage-val :lambda-list '(m))
(cl:defmethod book_storage-val ((m <FindBookGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader book_find-msg:book_storage-val is deprecated.  Use book_find-msg:book_storage instead.")
  (book_storage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindBookGoal>) ostream)
  "Serializes a message object of type '<FindBookGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'book_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'book_name))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'book_storage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'book_storage))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindBookGoal>) istream)
  "Deserializes a message object of type '<FindBookGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'book_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'book_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'book_storage) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'book_storage) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindBookGoal>)))
  "Returns string type for a message object of type '<FindBookGoal>"
  "book_find/FindBookGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindBookGoal)))
  "Returns string type for a message object of type 'FindBookGoal"
  "book_find/FindBookGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindBookGoal>)))
  "Returns md5sum for a message object of type '<FindBookGoal>"
  "f8216a57f9626349da1703f23af3e7f3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindBookGoal)))
  "Returns md5sum for a message object of type 'FindBookGoal"
  "f8216a57f9626349da1703f23af3e7f3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindBookGoal>)))
  "Returns full string definition for message of type '<FindBookGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string book_name~%string book_storage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindBookGoal)))
  "Returns full string definition for message of type 'FindBookGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string book_name~%string book_storage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindBookGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'book_name))
     4 (cl:length (cl:slot-value msg 'book_storage))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindBookGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FindBookGoal
    (cl:cons ':book_name (book_name msg))
    (cl:cons ':book_storage (book_storage msg))
))
