; Auto-generated. Do not edit!


(cl:in-package book_find-msg)


;//! \htmlinclude FindBookFeedback.msg.html

(cl:defclass <FindBookFeedback> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass FindBookFeedback (<FindBookFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindBookFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindBookFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name book_find-msg:<FindBookFeedback> is deprecated: use book_find-msg:FindBookFeedback instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <FindBookFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader book_find-msg:distance-val is deprecated.  Use book_find-msg:distance instead.")
  (distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindBookFeedback>) ostream)
  "Serializes a message object of type '<FindBookFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindBookFeedback>) istream)
  "Deserializes a message object of type '<FindBookFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindBookFeedback>)))
  "Returns string type for a message object of type '<FindBookFeedback>"
  "book_find/FindBookFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindBookFeedback)))
  "Returns string type for a message object of type 'FindBookFeedback"
  "book_find/FindBookFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindBookFeedback>)))
  "Returns md5sum for a message object of type '<FindBookFeedback>"
  "acff7fda0c683c872875f5c4b069f124")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindBookFeedback)))
  "Returns md5sum for a message object of type 'FindBookFeedback"
  "acff7fda0c683c872875f5c4b069f124")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindBookFeedback>)))
  "Returns full string definition for message of type '<FindBookFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%float64 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindBookFeedback)))
  "Returns full string definition for message of type 'FindBookFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%float64 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindBookFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindBookFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FindBookFeedback
    (cl:cons ':distance (distance msg))
))
