; Auto-generated. Do not edit!


(cl:in-package book_find-msg)


;//! \htmlinclude FindBookResult.msg.html

(cl:defclass <FindBookResult> (roslisp-msg-protocol:ros-message)
  ((arrived
    :reader arrived
    :initarg :arrived
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass FindBookResult (<FindBookResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindBookResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindBookResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name book_find-msg:<FindBookResult> is deprecated: use book_find-msg:FindBookResult instead.")))

(cl:ensure-generic-function 'arrived-val :lambda-list '(m))
(cl:defmethod arrived-val ((m <FindBookResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader book_find-msg:arrived-val is deprecated.  Use book_find-msg:arrived instead.")
  (arrived m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindBookResult>) ostream)
  "Serializes a message object of type '<FindBookResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'arrived) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindBookResult>) istream)
  "Deserializes a message object of type '<FindBookResult>"
    (cl:setf (cl:slot-value msg 'arrived) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindBookResult>)))
  "Returns string type for a message object of type '<FindBookResult>"
  "book_find/FindBookResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindBookResult)))
  "Returns string type for a message object of type 'FindBookResult"
  "book_find/FindBookResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindBookResult>)))
  "Returns md5sum for a message object of type '<FindBookResult>"
  "ea115e3ceb83b7b5fbcc7f283be1718c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindBookResult)))
  "Returns md5sum for a message object of type 'FindBookResult"
  "ea115e3ceb83b7b5fbcc7f283be1718c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindBookResult>)))
  "Returns full string definition for message of type '<FindBookResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool arrived ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindBookResult)))
  "Returns full string definition for message of type 'FindBookResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool arrived ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindBookResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindBookResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FindBookResult
    (cl:cons ':arrived (arrived msg))
))
