// Generated by gencpp from file arm_movement/MoveLinear.msg
// DO NOT EDIT!


#ifndef ARM_MOVEMENT_MESSAGE_MOVELINEAR_H
#define ARM_MOVEMENT_MESSAGE_MOVELINEAR_H

#include <ros/service_traits.h>


#include <arm_movement/MoveLinearRequest.h>
#include <arm_movement/MoveLinearResponse.h>


namespace arm_movement
{

struct MoveLinear
{

typedef MoveLinearRequest Request;
typedef MoveLinearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLinear
} // namespace arm_movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_movement::MoveLinear > {
  static const char* value()
  {
    return "c348f8d8cd3a80f54328aa4159009109";
  }

  static const char* value(const ::arm_movement::MoveLinear&) { return value(); }
};

template<>
struct DataType< ::arm_movement::MoveLinear > {
  static const char* value()
  {
    return "arm_movement/MoveLinear";
  }

  static const char* value(const ::arm_movement::MoveLinear&) { return value(); }
};


// service_traits::MD5Sum< ::arm_movement::MoveLinearRequest> should match
// service_traits::MD5Sum< ::arm_movement::MoveLinear >
template<>
struct MD5Sum< ::arm_movement::MoveLinearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_movement::MoveLinear >::value();
  }
  static const char* value(const ::arm_movement::MoveLinearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_movement::MoveLinearRequest> should match
// service_traits::DataType< ::arm_movement::MoveLinear >
template<>
struct DataType< ::arm_movement::MoveLinearRequest>
{
  static const char* value()
  {
    return DataType< ::arm_movement::MoveLinear >::value();
  }
  static const char* value(const ::arm_movement::MoveLinearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_movement::MoveLinearResponse> should match
// service_traits::MD5Sum< ::arm_movement::MoveLinear >
template<>
struct MD5Sum< ::arm_movement::MoveLinearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_movement::MoveLinear >::value();
  }
  static const char* value(const ::arm_movement::MoveLinearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_movement::MoveLinearResponse> should match
// service_traits::DataType< ::arm_movement::MoveLinear >
template<>
struct DataType< ::arm_movement::MoveLinearResponse>
{
  static const char* value()
  {
    return DataType< ::arm_movement::MoveLinear >::value();
  }
  static const char* value(const ::arm_movement::MoveLinearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_MOVEMENT_MESSAGE_MOVELINEAR_H
