// Generated by gencpp from file arm_movement/MoveLinearResponse.msg
// DO NOT EDIT!


#ifndef ARM_MOVEMENT_MESSAGE_MOVELINEARRESPONSE_H
#define ARM_MOVEMENT_MESSAGE_MOVELINEARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_movement
{
template <class ContainerAllocator>
struct MoveLinearResponse_
{
  typedef MoveLinearResponse_<ContainerAllocator> Type;

  MoveLinearResponse_()
    : success(false)
    , message()  {
    }
  MoveLinearResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::arm_movement::MoveLinearResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_movement::MoveLinearResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLinearResponse_

typedef ::arm_movement::MoveLinearResponse_<std::allocator<void> > MoveLinearResponse;

typedef boost::shared_ptr< ::arm_movement::MoveLinearResponse > MoveLinearResponsePtr;
typedef boost::shared_ptr< ::arm_movement::MoveLinearResponse const> MoveLinearResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_movement::MoveLinearResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_movement::MoveLinearResponse_<ContainerAllocator1> & lhs, const ::arm_movement::MoveLinearResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_movement::MoveLinearResponse_<ContainerAllocator1> & lhs, const ::arm_movement::MoveLinearResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_movement::MoveLinearResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_movement::MoveLinearResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_movement::MoveLinearResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::arm_movement::MoveLinearResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_movement/MoveLinearResponse";
  }

  static const char* value(const ::arm_movement::MoveLinearResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::arm_movement::MoveLinearResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLinearResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_movement::MoveLinearResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_movement::MoveLinearResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MOVEMENT_MESSAGE_MOVELINEARRESPONSE_H
