// Generated by gencpp from file book_find/FindBookResult.msg
// DO NOT EDIT!


#ifndef BOOK_FIND_MESSAGE_FINDBOOKRESULT_H
#define BOOK_FIND_MESSAGE_FINDBOOKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace book_find
{
template <class ContainerAllocator>
struct FindBookResult_
{
  typedef FindBookResult_<ContainerAllocator> Type;

  FindBookResult_()
    : arrived(false)  {
    }
  FindBookResult_(const ContainerAllocator& _alloc)
    : arrived(false)  {
  (void)_alloc;
    }



   typedef uint8_t _arrived_type;
  _arrived_type arrived;





  typedef boost::shared_ptr< ::book_find::FindBookResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::book_find::FindBookResult_<ContainerAllocator> const> ConstPtr;

}; // struct FindBookResult_

typedef ::book_find::FindBookResult_<std::allocator<void> > FindBookResult;

typedef boost::shared_ptr< ::book_find::FindBookResult > FindBookResultPtr;
typedef boost::shared_ptr< ::book_find::FindBookResult const> FindBookResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::book_find::FindBookResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::book_find::FindBookResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::book_find::FindBookResult_<ContainerAllocator1> & lhs, const ::book_find::FindBookResult_<ContainerAllocator2> & rhs)
{
  return lhs.arrived == rhs.arrived;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::book_find::FindBookResult_<ContainerAllocator1> & lhs, const ::book_find::FindBookResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace book_find

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::book_find::FindBookResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::book_find::FindBookResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_find::FindBookResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_find::FindBookResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_find::FindBookResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_find::FindBookResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::book_find::FindBookResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea115e3ceb83b7b5fbcc7f283be1718c";
  }

  static const char* value(const ::book_find::FindBookResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea115e3ceb83b7b5ULL;
  static const uint64_t static_value2 = 0xfbcc7f283be1718cULL;
};

template<class ContainerAllocator>
struct DataType< ::book_find::FindBookResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "book_find/FindBookResult";
  }

  static const char* value(const ::book_find::FindBookResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::book_find::FindBookResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"bool arrived \n"
;
  }

  static const char* value(const ::book_find::FindBookResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::book_find::FindBookResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arrived);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindBookResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::book_find::FindBookResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::book_find::FindBookResult_<ContainerAllocator>& v)
  {
    s << indent << "arrived: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arrived);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOOK_FIND_MESSAGE_FINDBOOKRESULT_H
