// Generated by gencpp from file book_find/FindBookFeedback.msg
// DO NOT EDIT!


#ifndef BOOK_FIND_MESSAGE_FINDBOOKFEEDBACK_H
#define BOOK_FIND_MESSAGE_FINDBOOKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace book_find
{
template <class ContainerAllocator>
struct FindBookFeedback_
{
  typedef FindBookFeedback_<ContainerAllocator> Type;

  FindBookFeedback_()
    : distance(0.0)  {
    }
  FindBookFeedback_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::book_find::FindBookFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::book_find::FindBookFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FindBookFeedback_

typedef ::book_find::FindBookFeedback_<std::allocator<void> > FindBookFeedback;

typedef boost::shared_ptr< ::book_find::FindBookFeedback > FindBookFeedbackPtr;
typedef boost::shared_ptr< ::book_find::FindBookFeedback const> FindBookFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::book_find::FindBookFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::book_find::FindBookFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::book_find::FindBookFeedback_<ContainerAllocator1> & lhs, const ::book_find::FindBookFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::book_find::FindBookFeedback_<ContainerAllocator1> & lhs, const ::book_find::FindBookFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace book_find

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::book_find::FindBookFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::book_find::FindBookFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_find::FindBookFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_find::FindBookFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_find::FindBookFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_find::FindBookFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::book_find::FindBookFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::book_find::FindBookFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::book_find::FindBookFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "book_find/FindBookFeedback";
  }

  static const char* value(const ::book_find::FindBookFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::book_find::FindBookFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"float64 distance\n"
"\n"
;
  }

  static const char* value(const ::book_find::FindBookFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::book_find::FindBookFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindBookFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::book_find::FindBookFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::book_find::FindBookFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOOK_FIND_MESSAGE_FINDBOOKFEEDBACK_H
