// Auto-generated. Do not edit!

// (in-package book_find.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FindBookGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.book_name = null;
      this.book_storage = null;
    }
    else {
      if (initObj.hasOwnProperty('book_name')) {
        this.book_name = initObj.book_name
      }
      else {
        this.book_name = '';
      }
      if (initObj.hasOwnProperty('book_storage')) {
        this.book_storage = initObj.book_storage
      }
      else {
        this.book_storage = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FindBookGoal
    // Serialize message field [book_name]
    bufferOffset = _serializer.string(obj.book_name, buffer, bufferOffset);
    // Serialize message field [book_storage]
    bufferOffset = _serializer.string(obj.book_storage, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FindBookGoal
    let len;
    let data = new FindBookGoal(null);
    // Deserialize message field [book_name]
    data.book_name = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [book_storage]
    data.book_storage = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.book_name.length;
    length += object.book_storage.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'book_find/FindBookGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f8216a57f9626349da1703f23af3e7f3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    string book_name
    string book_storage
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FindBookGoal(null);
    if (msg.book_name !== undefined) {
      resolved.book_name = msg.book_name;
    }
    else {
      resolved.book_name = ''
    }

    if (msg.book_storage !== undefined) {
      resolved.book_storage = msg.book_storage;
    }
    else {
      resolved.book_storage = ''
    }

    return resolved;
    }
};

module.exports = FindBookGoal;
